---

- import_tasks: quarterly_patches_prechecks_host.yml
  delegate_to: '{% if oracle_manage_patches_remote_stage %}{{ _oracle_manage_patches_host_quarterly_patches_item }}{% else %}localhost{% endif %}'
  tags:
    - oracle_manage_patches_import_tasks_quarterly_patches_prechecks_host

