---

- name: GRID post scripts | save 'opatch lsinventory' output
  shell: |
    $ORACLE_HOME/OPatch/opatch lsinventory | tee {{ oracle_manage_patches_log_dir }}/grid_home.post.{{ oracle_manage_patches_task }}.opatch-lsinventory.$(date +%Y-%m-%d_%H%M%S).log
  environment:
    ORACLE_HOME: '{{ oracle_gi_info.oracle_home }}'
  check_mode: no
  ignore_errors: yes
  register: _oracle_manage_patches_opatchlsinventory_output
  delegate_to: '{{ _oracle_manage_patches_host_patch_item }}'
  with_items:
    - "{{ oracle_manage_patches_rac_remote_nodes + [ inventory_hostname ] }}"
  loop_control:
    loop_var: _oracle_manage_patches_host_patch_item
    label: "[opatch lsinventory for :{{ oracle_gi_info.oracle_home }}; log: {{ oracle_manage_patches_log_dir }}/grid_home.post.{{ oracle_manage_patches_task }}.opatch-lsinventory.TIMESTAMP.log]"
  tags:
    - oracle_manage_patches_post_opatch_lsinventory

- include_tasks: display_stdout_lines_or_fail.yml
  vars:
    _oracle_manage_patches_debug: '{{ _oracle_manage_patches_lsinventory_item }}'
  with_items:
    - "{{ _oracle_manage_patches_opatchlsinventory_output.results|default([],true) }}"
  loop_control:
    loop_var: _oracle_manage_patches_lsinventory_item
    label: "[host: {{ _oracle_manage_patches_lsinventory_item._oracle_manage_patches_host_patch_item }}]"
  when: oracle_manage_patches_display_opatch_lsinventory_output or _oracle_manage_patches_lsinventory_item.stderr|default('',true) != '' or _oracle_manage_patches_lsinventory_item.rc|default(0,true) != 0
  tags:
    - oracle_manage_patches_post_display_opatch_lsinventory

