---

- name: shutdown databases | shutdown databases
  shell: |
    {% if _oracle_manage_patches_db_item.database_type == 'SINGLE' %}
    printf 'shutdown immediate\n' | $ORACLE_HOME/bin/sqlplus / as sysdba
    {% else %}
    $ORACLE_HOME/bin/srvctl stop database -d $DB_UNIQUE_NAME
    {% endif %}
    echo
  environment:
    ORACLE_HOME: '{{ _oracle_manage_patches_db_item.oracle_home }}'
    ORACLE_SID: '{{ _oracle_manage_patches_db_item.instance_name }}'
    DB_UNIQUE_NAME: '{{ _oracle_manage_patches_db_item.db_unique_name }}'
  with_items:
    - '{{ oracle_databases }}'
  loop_control:
    label: "[Shutting down DB_UNIQUE_NAME: {{ _oracle_manage_patches_db_item.db_unique_name }}; ORACLE_HOME: {{ _oracle_manage_patches_db_item.oracle_home }}]"
    loop_var: _oracle_manage_patches_db_item
  when:
    - _oracle_manage_patches_db_item.oracle_home == _oracle_manage_patches_oh_item.oracle_home
  tags:
    - oracle_manage_patches_shutdown_databases

